export const hardware = [
  {
    icon: null,
    author: null,
    image: null,
    name: "BentoBox",
    href: "https://scrubtier.co.uk/products/bentobox",
  },
  {
    icon: null,
    author: null,
    image: null,
    name: "Flatbox",
    href: "https://github.com/jfedor2/flatbox",
  },
  {
    icon: null,
    author: null,
    image: null,
    name: "Zandatsu",
    href: "https://github.com/Sharqo78/Zandatsu",
  },
  {
    icon: null,
    author: null,
    image: null,
    name: "Chastetiddy",
    href: "https://github.com/chastetiddy/chastity_device",
  },
  {
    icon: null,
    author: null,
    image: null,
    name: "BubbleBox",
    href: "https://github.com/UMS-Ultra/BubbleBox",
  },
  {
    icon: null,
    author: null,
    image: null,
    name: "CrushCounter",
    href: "https://github.com/SleepUnit/CrushCounter",
  },
  {
    icon: null,
    author: null,
    image: null,
    name: "Mavercade",
    href: "https://www.etsy.com/shop/Mavercade",
  },
  {
    icon: null,
    author: null,
    image: null,
    name: "Ultra-Arcade",
    href: "https://github.com/Ultra-Arcade/open-ua-cnc",
  },
];
